import { Router } from "express";
import * as c from "../controllers/warehouseController.js";
import role from "../middleware/roleMiddleware.js";
import validate from "../middleware/validateRequest.js";
import { layoutSchema } from "../utils/schemas.js";
const r = Router();
r.get("/", c.details);
r.get("/locations/:id/route", c.route);
r.put("/", role("admin", "manager"), validate(layoutSchema), c.update);
r.get("/racks/:rack/route", c.rackRoute);
export default r;
